name: Heal Injured Troops

node: heal_injured

priority: 45

trigger: healInjured.state.isAvailable

steps:
  - action: loop
    trigger: compareText(healInjured.state.isNext, "Heal Injured")
    steps:
      - if: # if current status -> "Heal"
          trigger: compareText(healInjured.state.statusHeal, "Heal")
          then:
            - click: heal_injured_help_button # Start healing
            - wait: 200ms
            - action: screenshot # check for resource replenishment window
              analyze:
                - name: healInjured.state.isReplenishAll
                  action: color_check
                  expectedColorBg: blue
                  threshold: 0.5

            - if:
                trigger: healInjured.state.isReplenishAll # If not enough resources
                then:
                  - click: healInjured.state.isReplenishAll # Take resources from bag
                  - wait: 200ms
                  - click: heal_injured_help_button # Start healing
                  - wait: 100ms
            - click: heal_injured_help_button # Request help

            - wait: 2s

            - action: screenshot # check for resource replenishment window
              analyze:
                - name: healInjured.state.isNext
                  action: text
                  type: string
                  threshold: 0.7
                - name: healInjured.state.statusHeal
                  action: text
                  type: string
                  threshold: 0.7
      - if: # if current status -> "Heal"
          trigger: alliance.state.isNeedSupport
          then:
            - click: alliance.state.isNeedSupport
            - action: screenshot               # 📸 Take screenshot of current screen
              analyze:
                - name: alliance.state.isNeedSupport
                  action: exist
                  threshold: 0.7
      - action: screenshot # update healing button status
        analyze:
          - name: healInjured.state.statusHeal
            action: text
            type: string
            threshold: 0.7
          - name: screenState.titleFact
            action: text
            type: string
            threshold: 0.9
      - if: # fallback: in case of misclick when clicking on help
          trigger: compareText(screenState.titleFact, "Chat")
          then:
            - action: loop_stop
