name: Alliance Chest Gifts

node: alliance_chest_gift

trigger: alliance.state.isGiftClaimAllButton || alliance.state.isClaimButton

priority: 20

steps:
  - if: # If "Claim All" button is available, just click it
      trigger: alliance.state.isGiftClaimAllButton
      then:
        - click: alliance.state.isGiftClaimAllButton
        - wait: 200ms
        - click: exploration_claim_confirmation_button
        - wait: 500ms
        - click: tap_anywhere_to_exit
        - wait: 200ms
  - if: # If "Claim All" button is not available, find and click each "Claim" button
      trigger: "!alliance.state.isGiftClaimAllButton && alliance.state.isClaimButton"
      then:
        - action: loop
          trigger: alliance.state.isClaimButton
          steps:
            - click: alliance.state.isClaimButton
            - wait: 400ms
            - action: screenshot
              analyze:
                - name: alliance.state.isClaimButton
                  action: findIcon
                  threshold: 0.7
                  saveAsRegion: true

