# TODO: check that there are enough resources and buy more if not enough
# TODO: learn to parse 4.5M as 4500000 for correct trigger operation

name: Chief Resource Claim

node: chief_orders

trigger: chief.state.isUrgentMobilization && chief.state.isProductivityDay && chief.state.isRushJob

priority: 10

# To get maximum resources we need to execute a sequential combo of three governor orders
steps:
  # Click on "Mobilization" button
  - click: chief.state.isUrgentMobilization
  - wait: 3s
  - click: chief_orders_enact # Order confirmation
  - wait: 3s
  - click: to_chief_orders # After executing the order we are redirected to the city page, so we need to return to the governor page
  - wait: 200ms # for animation rendering

  # Click on "Universal Help" button
  - click: chief.state.isProductivityDay
  - wait: 3s
  - click: chief_orders_enact
  - wait: 3s
  - click: to_chief_orders # After executing the order we are redirected to the city page, so we need to return to the governor page
  - wait: 200ms # for animation rendering

  # Click on "Special Order" button
  - click: chief.state.isRushJob
  - wait: 3s
  - click: chief_orders_enact
  - wait: 5s
  - click: to_chief_orders # skip reward notification
  - wait: 500ms
  - click: to_chief_orders # After executing the order we are redirected to the city page, so we need to return to the governor page

  - pushUsecase:
      - trigger: true # Always trigger
        list:
          - name: Check Chief # Update information about governor orders