name: "❄️ Start Rally to Polar Terror (Max 3/day)"

node: world_map

ttl: 8h  # Limit to 3 times per day

trigger: "rally.state.canStart == true && rally.state.target == 'PolarTerror' && rally.state.dailyPolarCount < 3"

steps:
  - click: to_world_map
  - wait: 1s

  - click: polar_terror_icon
  - wait: 500ms

  - click: rally_start_button
  - wait: 300ms

  - click: rally_confirm_button

  - increment: rally.state.dailyPolarCount
