name: "🔄 Auto-Update Rally Join Setting"

node: alliance_war

ttl: 5h  # Update every 5 hours

trigger: "true"

steps:
  - click: auto_rally_settings_button
  - wait: 300ms

  - click: auto_rally_toggle_on    # Enable auto-join rally
  - wait: 300ms

  - click: auto_rally_close_button
