# TODO:
# 1. Check that x2 and auto are activated (buttons are yellow), if not - enable them
# 2. Make quick_deploy_button a separate usecase with higher priority

name: Exploration Battle

node: exploration_battle

trigger: "double(exploration.state.myPower) * 1.2 >= double(exploration.state.enemyPower)"

ttl: 10h

priority: 10

cron: "0 */12 * * *" # every 12 hours

steps:
  - click: quick_deploy_button
  - wait: 200ms
  - click: exploration_fight_button
  - wait: 10s

  - action: loop
    # Loop continues while lowerAscii(battleStatus) contains neither "defeat" nor "victory"
    trigger: '!(exploration.state.battleStatus.lowerAscii().contains("defeat") || exploration.state.battleStatus.lowerAscii().contains("victory"))'
    steps:
      - action: screenshot
        analyze:
          - name: exploration.state.battleStatus
            action: text
            type: string
            threshold: 0.5

      - if:
          trigger: 'exploration.state.battleStatus.lowerAscii().contains("defeat")'
          then:
            - action: exploration_battle_back_area
            - action: loop_stop

      - if:
          trigger: 'exploration.state.battleStatus.lowerAscii().contains("victory")'
          then:
            - click: exploration_battle_continue_button
            - wait: 100ms
            - click: exploration_fight_button
            - action: reset
              set: exploration.state.battleStatus
              to: ""

      - wait: 1s

  - action: reset
    set: exploration.state.battleStatus
    to: ""
