name: VIP Add

trigger: vip.state.isVIPAddAvailable

node: vip_add

priority: 10

steps:
  - action: loop
    trigger: vip.state.isVIPAddAvailable
    steps:
      - if: # If multiplier button is available, click it
          trigger: vip.state.isVIPAddAvailableX
          then:
            - click: vip.state.isVIPAddAvailableX
      - if: # If multiplier button is not available, click regular VIP button
          trigger: "!vip.state.isVIPAddAvailableX"
          then:
            - click: vip.state.isVIPAddAvailable
      - action: screenshot           # 📸 After clicking, take screenshot again and update state
        analyze:
          - name: vip.state.isVIPAddAvailable
            action: color_check
            expectedColorBg: green
            threshold: 0.5
          - name: vip.state.isVIPAddAvailableX
            action: color_check
            expectedColorBg: green
            threshold: 0.5
      - click: vip_add_any_click # Click anywhere on screen, just in case

  - pushUsecase:
      - trigger: vip.state.isAdd
        list:
          - name: Check VIP
